-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "price" SET DEFAULT 0.00,
ALTER COLUMN "offer" SET DEFAULT 0.00,
ALTER COLUMN "offerPrice" SET DEFAULT 0.00,
ALTER COLUMN "quantity" SET DEFAULT 0.00;
